### ISSUE TITLE
items generating without container?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#100]
possibly because map adds damage (craters etc.) which can destroy these containers?

normally this wouldn't be much of a problem but with underground bunkers settlers will immediately head outside on a suicide run to pick these items up (and because of interiors being hidden player can't even see were these items are)... 

also because I'm using existing stairs my base remained hidden ;)

[0903 schorched wtf.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7917883/0903.schorched.wtf.zip)

![image](https://user-images.githubusercontent.com/91120787/150630295-5357ee3c-ace7-4b88-8358-ba43d50a411f.png)

**Comment by SerialKicked** [comment]
Good find, I will make a pass at removing "wild" items like that from the map after the proc gen bombardment.

Oh, didn't think about that regarding those stairs. :/
Mmhhhh, I think I'll make it so that the base gets revealed the moment you build anything above ground, stairs or not. That way you can still explore the surface using existing stairs, but won't be able to get traders or launch expeditions without revealing yourself.
