### ISSUE TITLE
lot of sick mutants?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#111]
was sickness rate increased? because I'm having a lot of sick mutants... and mutants don't seem to have access to health care law

[0906 test.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/8052811/0906.test.zip)

settlers/mutants also still get stuck doing stuff and not taking care of their needs, could this cause sickness?

![image](https://user-images.githubusercontent.com/91120787/153697941-167a7f00-6ed0-40bf-8cc9-cc3c854d727b.png)

**Comment by SerialKicked** [comment]
Not sure. 

Getting "sick" has several meaning:

- bad cough event. transmissible sickness that spawn on a few people and which get transmitted while chatting and can evolve into either a small thing or a more annoying one. It can last very long and not get cured until you have (plant/antibio) medicine. Makes sickness (the need) goes up.

- sickness caused by dead bodies, or attacks, or dirty water, or .... tons of other factors without the event. 

High sickness makes it more difficult for people to deal with their other needs, yes, to some extent. I'd love to have a look at that save, tho. To see what's up.
