### ISSUE TITLE
Drafting particular characters

### ISSUE THREAD

**Issue by FulcrumA** [AnarkisGaming/ATC-Feedback#136]
**Posting here an entry from Discord, as requested:**

> Being able to "draft" only some characters would be a great help. It actually really disturbs things when one doesn't have dedicated soldiers to use current Combat toggle (especially early game) as it basically forces whole colony to drop what they're doing, just because I want to draft one guy to finish off some injured enemy somewhere.

**Comment by IvanBajlo** [comment]
if you disable military skill they won't get drafted and continue working (but this creates danger of them running into enemies)... this could also go into combat tutorial ;-)

unfortunately this resets each time you do anything in job manager... so best do that one first

![image](https://user-images.githubusercontent.com/91120787/192254143-b7b3cff8-30ad-40b0-a9e6-c14acc2d46ab.png)

**Comment by FulcrumA** [comment]
Yes, it's some workaround but very clunky long-term, forcing horrible amounts of micromanagement as every time you'd have to manually enter menu, navigate to military job permission, take everyone but the characters you want to draft at the moment out of it, come back to the game, send them to do whatever they are to do, then after their job is done come back to population screen, set again all other intended fighters up for military duty and return to the game again. Navigation of the menus would often take longer time than actual assignment you want to send some chosen fighter on.

**Comment by IvanBajlo** [comment]
you can assign soldier settlers to patrol zone and then simply select all of them with mouse and draft only them

![image](https://user-images.githubusercontent.com/91120787/192271854-4145a056-36e8-498b-b8a3-2e9e97f614d5.png)

**Comment by SerialKicked** [comment]
There are already like 4 different ways to do that. 

1) You can click on someone and press the daft button on their own menu

2) You can mouse-lasso a group of people and draft/undraft them all at once

3) You can assign/remove your favorite fighters to a control group and call them with the press of a single key. See encyclopedia.

4) You can use patrol zones to setup guard posts, assigning whoever you want to the task.

For the love of god, don't micro-manage military skills. This is not Rimworld. Just disable military on your main doctor and scientist if you wish, to keep them safe, and use any of the above methods instead of mobilizing your whole base each time a spider come visit.

**Comment by IvanBajlo** [comment]
there are control groups? :D 

https://steamcommunity.com/sharedfiles/filedetails/?id=2867957647

**Comment by SerialKicked** [comment]
> there are control groups? :D
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=2867957647

Yep, since 1.0.

_One_ control group. Multiple really didn't feel needed, and I'm not reassigning the 1-9 keys. IIRC the default key is G. I edited the combat article in the encyclopedia with a chapter explaining how to use it (it's in like any RTS really, shift/ctrl+G to add/set, G alone to toggle group activation).

**Comment by IvanBajlo** [comment]
ctrl+1-9 for teams to create massive army and turn game into tactical RTS :D
