### ISSUE TITLE
bizarre game I left running during night :D

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#49]
it seems nobody is purifying water or cooking food despite everyone starving and drinking dirty water... can lack of private bedrooms result in this insanity? or there is some other glitch in question?

[0862 insane.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7365304/0862.insane.zip)

this is starting save if you want to leave it running over night yourself ;-)
[0862 test.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7365342/0862.test.zip)

**Comment by SerialKicked** [comment]
There's so many problems in that save, I mean in the code. It's as useful as it's depressing. I fixing all the things i can find.

**Comment by SerialKicked** [comment]
Ok, got your save under control:

Bugs found & addressed:
+ Logic issue in last factory patch, where worker jobs would get canceled under some erroneous situation (minor, rare)
+ When no food is avail, ppl start looking for tiles with food waiting to be processed, the test wouldn't blacklist fodder, causing people to go on a loop of trying to get food and failing instead of taking care on other needs as long as there's fodder on a tile
+ In the same test, if the tile is not accessible, it would still be processed as OK, with the same problem

Balance changes:
+ AI: People who are critical/starving for food AND working on a "cooking" job will no longer see that task interrupted by any other game process (other needs, brawl, whatever)
+ AI: Minor change in logic preventing people with ZERO work ethics from being absolutely worthless. 

That was enough to make people sleep & work again properly. However, there's a large design issue in the base. The underground food ingredient storage is super far away from the kitchen. It would have been best to have a second kitchen nearby instead.
