### ISSUE TITLE
Why does rain collector gets prioritized over everything else?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#5]
It would be useful to be able to disable/enable all collectors with single click.

**Comment by SerialKicked** [comment]
The auto prioritization is  old code, from when the game was a lot worse at doing its job. It works really well when used like intended, by having a few collectors for the early game. It wasn't intended that the player would spam hundreds of them instead of using most cost efficient wells.

The collector's menu will get the factory menu treatment soon.
