### ISSUE TITLE
mountains no longer drop resources?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#71]
no more gold, metal, clay blocks, coal etc.

**Comment by SerialKicked** [comment]
They should (and do in my save, but haven't looked in a new game yet), will have a look to see what's up

**Comment by SerialKicked** [comment]
Ok, that one was quite esoteric and only happens under some conditions, but I found out why. I'll get that fixed in Friday patch. 

It's pretty much set after generating a map, so, in the meantime, I don't think it would continue to happen in a current save if you just quit/launch the game again. Not 100% sure.
